import { unstable_cacheLife } from 'next/cache'

export async function findManyEvents(q: string): Promise<{
  error: null | Error
  data: Record<string, any[]>
}> {
  'use cache'
  unstable_cacheLife('minutes')

  const json = Promise.resolve({
    error: null,
    data: {
      '2025-08-18': [
        {
          display_title: '服務業表現指數',
          id: '1127500',
          previous_number: '47.3',
          consensus_number: null,
          actual_number: '48.9',
          revised_number: null,
          publish_at: '2025-08-17T22:30:00+00:00',
          country: 'NZD',
          unit: null,
        },
        {
          display_title: 'Rightmove平均房屋要價指數年率',
          id: '1127502',
          previous_number: '0.10',
          consensus_number: null,
          actual_number: '0.3',
          revised_number: null,
          publish_at: '2025-08-17T23:01:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: 'Rightmove平均房屋要價指數月率',
          id: '1127501',
          previous_number: '-1.20',
          consensus_number: null,
          actual_number: '-1.3',
          revised_number: null,
          publish_at: '2025-08-17T23:01:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: '今日有1120億元7天期逆回購到期。',
          id: '1127405',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-18T01:20:00+00:00',
          country: 'CNY',
          unit: null,
        },
        {
          display_title: '第三產業活動指數月率',
          id: '1127503',
          previous_number: '0.60',
          consensus_number: '0.20',
          actual_number: '0.5',
          revised_number: null,
          publish_at: '2025-08-18T04:30:00+00:00',
          country: 'JPY',
          unit: '%',
        },
        {
          display_title: '工業產出年率',
          id: '1127504',
          previous_number: '8.50',
          consensus_number: null,
          actual_number: '-0.1',
          revised_number: '8.9',
          publish_at: '2025-08-18T06:30:00+00:00',
          country: 'CHF',
          unit: '%',
        },
        {
          display_title: '季調後貿易帳',
          id: '1127505',
          previous_number: '162',
          consensus_number: null,
          actual_number: '28',
          revised_number: '156',
          publish_at: '2025-08-18T09:00:00+00:00',
          country: 'EUR',
          unit: '億歐元',
        },
        {
          display_title: '未季調貿易帳',
          id: '1127506',
          previous_number: '162',
          consensus_number: '130',
          actual_number: '70',
          revised_number: '165',
          publish_at: '2025-08-18T09:00:00+00:00',
          country: 'EUR',
          unit: '億歐元',
        },
        {
          display_title: '全國經濟信心指數',
          id: '1127507',
          previous_number: '52',
          consensus_number: null,
          actual_number: '51.2',
          revised_number: null,
          publish_at: '2025-08-18T12:00:00+00:00',
          country: 'CAD',
          unit: null,
        },
        {
          display_title: '新屋開工',
          id: '1127508',
          previous_number: '28.37',
          consensus_number: '26.5',
          actual_number: '29.41',
          revised_number: '28.35',
          publish_at: '2025-08-18T12:15:00+00:00',
          country: 'CAD',
          unit: '萬戶',
        },
        {
          display_title: '投資者淨買入海外證券',
          id: '1127642',
          previous_number: '133.7',
          consensus_number: null,
          actual_number: '90.4',
          revised_number: '134.6',
          publish_at: '2025-08-18T12:30:00+00:00',
          country: 'CAD',
          unit: '億加元',
        },
        {
          display_title: '海外投資者淨買入加拿大證券',
          id: '1127509',
          previous_number: '-27.9',
          consensus_number: null,
          actual_number: '7.1',
          revised_number: '-62.9',
          publish_at: '2025-08-18T12:30:00+00:00',
          country: 'CAD',
          unit: '億加元',
        },
      ],
      '2025-08-19': [
        {
          display_title: 'NAHB房產市場指數',
          id: '1127510',
          previous_number: '33',
          consensus_number: '34',
          actual_number: '32',
          revised_number: null,
          publish_at: '2025-08-18T14:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '3個月國債競拍-得標利率',
          id: '1127511',
          previous_number: '4.15',
          consensus_number: null,
          actual_number: '4.13',
          revised_number: null,
          publish_at: '2025-08-18T15:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '3個月國債競拍-得標利率配置百分比',
          id: '1127643',
          previous_number: '24.77',
          consensus_number: null,
          actual_number: '51.22',
          revised_number: null,
          publish_at: '2025-08-18T15:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '3個月國債競拍-投標倍數',
          id: '1127512',
          previous_number: '2.64',
          consensus_number: null,
          actual_number: '2.7',
          revised_number: null,
          publish_at: '2025-08-18T15:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '6個月國債競拍-得標利率',
          id: '1127513',
          previous_number: '3.97',
          consensus_number: null,
          actual_number: '3.945',
          revised_number: null,
          publish_at: '2025-08-18T15:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '6個月國債競拍-得標利率配置百分比',
          id: '1127644',
          previous_number: '27.15',
          consensus_number: null,
          actual_number: '75.09',
          revised_number: null,
          publish_at: '2025-08-18T15:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '6個月國債競拍-投標倍數',
          id: '1127514',
          previous_number: '3.21',
          consensus_number: null,
          actual_number: '2.95',
          revised_number: null,
          publish_at: '2025-08-18T15:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '歐洲領導人抵達白宮。',
          id: '1127779',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-18T16:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title:
            '美國總統特朗普在華盛頓與烏克蘭總統澤連斯基舉行雙邊會晤。',
          id: '1127771',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-18T17:15:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '美國總統特朗普與歐洲領導人舉行多邊會議。',
          id: '1127780',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-18T19:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '輸入PPI季率',
          id: '1127516',
          previous_number: '2.90',
          consensus_number: null,
          actual_number: '0.6',
          revised_number: null,
          publish_at: '2025-08-18T22:45:00+00:00',
          country: 'NZD',
          unit: '%',
        },
        {
          display_title: '輸入PPI年率',
          id: '1127646',
          previous_number: '5.3',
          consensus_number: null,
          actual_number: '4.5',
          revised_number: null,
          publish_at: '2025-08-18T22:45:00+00:00',
          country: 'NZD',
          unit: '%',
        },
        {
          display_title: '輸出PPI季率',
          id: '1127515',
          previous_number: '2.10',
          consensus_number: null,
          actual_number: '0.6',
          revised_number: null,
          publish_at: '2025-08-18T22:45:00+00:00',
          country: 'NZD',
          unit: '%',
        },
        {
          display_title: '輸出PPI年率',
          id: '1127645',
          previous_number: '4.7',
          consensus_number: null,
          actual_number: '4.2',
          revised_number: null,
          publish_at: '2025-08-18T22:45:00+00:00',
          country: 'NZD',
          unit: '%',
        },
        {
          display_title: '西太平洋/墨爾本消費者信心指數',
          id: '1127518',
          previous_number: '93.1',
          consensus_number: null,
          actual_number: '98.5',
          revised_number: null,
          publish_at: '2025-08-19T00:30:00+00:00',
          country: 'AUD',
          unit: null,
        },
        {
          display_title: '西太平洋/墨爾本消費者信心指數月率',
          id: '1127517',
          previous_number: '0.60',
          consensus_number: null,
          actual_number: '5.7',
          revised_number: null,
          publish_at: '2025-08-19T00:30:00+00:00',
          country: 'AUD',
          unit: '%',
        },
        {
          display_title: '今日有1146億元7天期逆回購到期。',
          id: '1127418',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T01:20:00+00:00',
          country: 'CNY',
          unit: null,
        },
        {
          display_title: '澳洲聯儲支付政策主管Ellis Connolly出席爐邊談話活動。',
          id: '1127417',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T04:50:00+00:00',
          country: 'AUD',
          unit: null,
        },
        {
          display_title: '季調後經常帳',
          id: '1127519',
          previous_number: '323',
          consensus_number: null,
          actual_number: '358',
          revised_number: null,
          publish_at: '2025-08-19T08:00:00+00:00',
          country: 'EUR',
          unit: '億歐元',
        },
        {
          display_title: '未季調經常帳',
          id: '1127647',
          previous_number: '10.2',
          consensus_number: null,
          actual_number: '389',
          revised_number: null,
          publish_at: '2025-08-19T08:00:00+00:00',
          country: 'EUR',
          unit: '億歐元',
        },
        {
          display_title: '三個月失業率',
          id: '1127520',
          previous_number: '3.50',
          consensus_number: null,
          actual_number: '3.7',
          revised_number: null,
          publish_at: '2025-08-19T08:30:00+00:00',
          country: 'HKD',
          unit: '%',
        },
        {
          display_title:
            '法國總統馬克龍和英國首相斯塔默共同主持烏克蘭意願聯盟會議。',
          id: '1127801',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T10:15:00+00:00',
          country: 'EUR',
          unit: null,
        },
        {
          display_title:
            '國新辦舉行新聞發布會，介紹「十四五」時期體育強國建設成就。',
          id: '1127781',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T11:00:00+00:00',
          country: 'CNY',
          unit: null,
        },
        {
          display_title: '美國財長貝森特發表講話。',
          id: '1127802',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T11:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '全球乳制品貿易價格指數',
          id: '1127686',
          previous_number: '0.7',
          consensus_number: null,
          actual_number: '-0.3',
          revised_number: null,
          publish_at: '2025-08-19T12:00:00+00:00',
          country: 'NZD',
          unit: '%',
        },
        {
          display_title: '美國總統特朗普發表講話。',
          id: '1127803',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T12:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: 'CPI年率',
          id: '1127524',
          previous_number: '1.90',
          consensus_number: '1.8',
          actual_number: '1.7',
          revised_number: null,
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: 'CPI月率',
          id: '1127522',
          previous_number: '0.10',
          consensus_number: '0.3',
          actual_number: '0.3',
          revised_number: null,
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: '新屋開工年化月率',
          id: '1127525',
          previous_number: '4.60',
          consensus_number: '-1.8',
          actual_number: '5.2',
          revised_number: '5.9',
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '新屋開工總數年化',
          id: '1127521',
          previous_number: '132.1',
          consensus_number: '129',
          actual_number: '142.8',
          revised_number: '135.8',
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'USD',
          unit: '萬戶',
        },
        {
          display_title: '核心CPI年率',
          id: '1127649',
          previous_number: '2.7',
          consensus_number: null,
          actual_number: '2.6',
          revised_number: null,
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: '核心CPI月率',
          id: '1127648',
          previous_number: '0.1',
          consensus_number: null,
          actual_number: '0.1',
          revised_number: null,
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: '營建許可月率',
          id: '1127526',
          previous_number: '-0.10',
          consensus_number: '-0.5',
          actual_number: '-2.8',
          revised_number: null,
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '營建許可總數',
          id: '1127523',
          previous_number: '139.3',
          consensus_number: '138.6',
          actual_number: '135.4',
          revised_number: null,
          publish_at: '2025-08-19T12:30:00+00:00',
          country: 'USD',
          unit: '萬戶',
        },
        {
          display_title: '當周紅皮書商業零售銷售年率',
          id: '1127402',
          previous_number: '5.7',
          consensus_number: null,
          actual_number: '5.9',
          revised_number: null,
          publish_at: '2025-08-19T12:55:00+00:00',
          country: 'USD',
          unit: '%',
        },
      ],
      '2025-08-20': [
        {
          display_title: '美聯儲理事鮑曼發表講話。',
          id: '1127804',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T14:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '6周國債競拍-得標利率',
          id: '1127527',
          previous_number: '4.27',
          consensus_number: null,
          actual_number: '4.25',
          revised_number: null,
          publish_at: '2025-08-19T15:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '6周國債競拍-投標倍數',
          id: '1127528',
          previous_number: '2.4',
          consensus_number: null,
          actual_number: '2.57',
          revised_number: null,
          publish_at: '2025-08-19T15:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '美聯儲理事鮑曼發表講話。',
          id: '1127775',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-19T18:10:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '當周API原油庫存',
          id: '1090438',
          previous_number: '151.9',
          consensus_number: '-158.7',
          actual_number: '-241.7',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周API原油進口',
          id: '1090443',
          previous_number: '34',
          consensus_number: null,
          actual_number: '36.7',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周API取暖油庫存',
          id: '1090442',
          previous_number: '51.9',
          consensus_number: null,
          actual_number: '9.2',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周API庫欣原油庫存',
          id: '1090441',
          previous_number: '-60.1',
          consensus_number: null,
          actual_number: '-11.2',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周API成品油進口',
          id: '1090444',
          previous_number: '-9.4',
          consensus_number: null,
          actual_number: '41.2',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周API投產原油量',
          id: '1090445',
          previous_number: '4.3',
          consensus_number: null,
          actual_number: '4.7',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周API汽油庫存',
          id: '1090439',
          previous_number: '-178.2',
          consensus_number: '-96.3',
          actual_number: '-95.6',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周API精煉油庫存',
          id: '1090440',
          previous_number: '29.5',
          consensus_number: '42.2',
          actual_number: '53.5',
          revised_number: null,
          publish_at: '2025-08-19T20:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '商品出口年率',
          id: '1127531',
          previous_number: '-0.50',
          consensus_number: '-2.1',
          actual_number: '-2.6',
          revised_number: null,
          publish_at: '2025-08-19T23:50:00+00:00',
          country: 'JPY',
          unit: '%',
        },
        {
          display_title: '商品進口年率',
          id: '1127532',
          previous_number: '0.20',
          consensus_number: '-10.4',
          actual_number: '-7.5',
          revised_number: '0.30',
          publish_at: '2025-08-19T23:50:00+00:00',
          country: 'JPY',
          unit: '%',
        },
        {
          display_title: '季調後商品貿易帳',
          id: '1127530',
          previous_number: '-2354.59',
          consensus_number: '-672',
          actual_number: '-3029.7',
          revised_number: null,
          publish_at: '2025-08-19T23:50:00+00:00',
          country: 'JPY',
          unit: '億日元',
        },
        {
          display_title: '未季調商品貿易帳',
          id: '1127529',
          previous_number: '1531',
          consensus_number: '1962',
          actual_number: '-1175',
          revised_number: '1521',
          publish_at: '2025-08-19T23:50:00+00:00',
          country: 'JPY',
          unit: '億日元',
        },
        {
          display_title: '核心機械訂單年率',
          id: '1127534',
          previous_number: '4.40',
          consensus_number: '5',
          actual_number: '7.6',
          revised_number: null,
          publish_at: '2025-08-19T23:50:00+00:00',
          country: 'JPY',
          unit: '%',
        },
        {
          display_title: '核心機械訂單月率',
          id: '1127533',
          previous_number: '-0.60',
          consensus_number: '-1.00',
          actual_number: '3',
          revised_number: null,
          publish_at: '2025-08-19T23:50:00+00:00',
          country: 'JPY',
          unit: '%',
        },
        {
          display_title: '一年期貸款市場報價利率',
          id: '1127535',
          previous_number: '3.00',
          consensus_number: '3.00',
          actual_number: '3',
          revised_number: null,
          publish_at: '2025-08-20T01:00:00+00:00',
          country: 'CNY',
          unit: '%',
        },
        {
          display_title: '五年期貸款市場報價利率',
          id: '1127536',
          previous_number: '3.50',
          consensus_number: '3.50',
          actual_number: '3.5',
          revised_number: null,
          publish_at: '2025-08-20T01:00:00+00:00',
          country: 'CNY',
          unit: '%',
        },
        {
          display_title: '今日有1185億元7天期逆回購到期。',
          id: '1127429',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T01:20:00+00:00',
          country: 'CNY',
          unit: null,
        },
        {
          display_title: '國新辦將舉行新聞發布會，介紹閱兵准備工作有關情況。',
          id: '1127783',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T02:00:00+00:00',
          country: 'CNY',
          unit: null,
        },
        {
          display_title: '新西蘭聯儲公布利率決議。',
          id: '1089756',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T02:00:00+00:00',
          country: 'NZD',
          unit: null,
        },
        {
          display_title:
            '澳洲聯儲助理主席麥克菲及瓊斯出席澳洲貨幣經濟學會網絡研討會的小組討論。',
          id: '1127426',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T02:00:00+00:00',
          country: 'AUD',
          unit: null,
        },
        {
          display_title: '聯儲利率決定',
          id: '1127537',
          previous_number: '3.25',
          consensus_number: '3.00',
          actual_number: '3',
          revised_number: null,
          publish_at: '2025-08-20T02:00:00+00:00',
          country: 'NZD',
          unit: '%',
        },
        {
          display_title: '新西蘭聯儲主席霍克斯比召開貨幣政策新聞發布會。',
          id: '1089364',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T03:00:00+00:00',
          country: 'NZD',
          unit: null,
        },
        {
          display_title: 'CPI年率',
          id: '1127539',
          previous_number: '3.60',
          consensus_number: '3.7',
          actual_number: '3.8',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: 'CPI月率',
          id: '1127538',
          previous_number: '0.30',
          consensus_number: '-0.1',
          actual_number: '0.1',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: 'PPI年率',
          id: '1127545',
          previous_number: '-1.30',
          consensus_number: '-1.3',
          actual_number: '-1.5',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'DE',
          unit: '%',
        },
        {
          display_title: 'PPI月率',
          id: '1127544',
          previous_number: '0.10',
          consensus_number: '0.1',
          actual_number: '-0.1',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'DE',
          unit: '%',
        },
        {
          display_title: '核心CPI年率',
          id: '1127540',
          previous_number: '3.70',
          consensus_number: '3.7',
          actual_number: '3.8',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: '核心CPI月率',
          id: '1127650',
          previous_number: '0.4',
          consensus_number: '0.1',
          actual_number: '0.2',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: '核心零售物價指數年率',
          id: '1127543',
          previous_number: '4.30',
          consensus_number: null,
          actual_number: '4.7',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: '零售物價指數年率',
          id: '1127542',
          previous_number: '4.40',
          consensus_number: '4.5',
          actual_number: '4.8',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: '零售物價指數月率',
          id: '1127541',
          previous_number: '0.40',
          consensus_number: '0.1',
          actual_number: '0.4',
          revised_number: null,
          publish_at: '2025-08-20T06:00:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: '歐洲央行行長拉加德出席世界經濟論壇的一個會議。',
          id: '1127776',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T07:10:00+00:00',
          country: 'CHF',
          unit: null,
        },
        {
          display_title: '外銷訂單年率',
          id: '1127548',
          previous_number: '24.60',
          consensus_number: '15',
          actual_number: '15.2',
          revised_number: null,
          publish_at: '2025-08-20T08:00:00+00:00',
          country: 'TWD',
          unit: '%',
        },
        {
          display_title: '經常帳',
          id: '1127549',
          previous_number: '302.3',
          consensus_number: null,
          actual_number: '362.3',
          revised_number: null,
          publish_at: '2025-08-20T08:20:00+00:00',
          country: 'TWD',
          unit: '億美元',
        },
        {
          display_title: 'DCLG房價指數年率',
          id: '1127550',
          previous_number: '3.90',
          consensus_number: null,
          actual_number: '3.7',
          revised_number: null,
          publish_at: '2025-08-20T08:30:00+00:00',
          country: 'GBP',
          unit: '%',
        },
        {
          display_title: 'CPI年率終值',
          id: '1127551',
          previous_number: '2.00',
          consensus_number: '2',
          actual_number: '2',
          revised_number: null,
          publish_at: '2025-08-20T09:00:00+00:00',
          country: 'EUR',
          unit: '%',
        },
        {
          display_title: 'CPI月率終值',
          id: '1127552',
          previous_number: '0.00',
          consensus_number: '0',
          actual_number: '0',
          revised_number: null,
          publish_at: '2025-08-20T09:00:00+00:00',
          country: 'EUR',
          unit: '%',
        },
        {
          display_title: '核心CPI年率終值',
          id: '1127657',
          previous_number: '2.4',
          consensus_number: '2.4',
          actual_number: '2.4',
          revised_number: null,
          publish_at: '2025-08-20T09:00:00+00:00',
          country: 'EUR',
          unit: '%',
        },
        {
          display_title: '核心CPI月率終值',
          id: '1127658',
          previous_number: '-0.1',
          consensus_number: null,
          actual_number: '-0.1',
          revised_number: null,
          publish_at: '2025-08-20T09:00:00+00:00',
          country: 'EUR',
          unit: '%',
        },
        {
          display_title: '當周MBA30年期固定抵押貸款利率',
          id: '1127700',
          previous_number: '6.67',
          consensus_number: null,
          actual_number: '6.68',
          revised_number: null,
          publish_at: '2025-08-20T11:00:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '當周MBA抵押貸款再融資活動指數',
          id: '1127697',
          previous_number: '956.2',
          consensus_number: null,
          actual_number: '926.1',
          revised_number: null,
          publish_at: '2025-08-20T11:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '當周MBA抵押貸款申請活動指數',
          id: '1127698',
          previous_number: '281.1',
          consensus_number: null,
          actual_number: '277.1',
          revised_number: null,
          publish_at: '2025-08-20T11:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '當周MBA抵押貸款購買指數',
          id: '1127699',
          previous_number: '160.2',
          consensus_number: null,
          actual_number: '160.3',
          revised_number: null,
          publish_at: '2025-08-20T11:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '新屋價格指數月率',
          id: '1127701',
          previous_number: '-0.2',
          consensus_number: null,
          actual_number: '-0.1',
          revised_number: null,
          publish_at: '2025-08-20T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
      ],
      '2025-08-21': [
        {
          display_title: '當周EIA俄克拉荷馬州庫欣原油庫存',
          id: '1127554',
          previous_number: '4.5',
          consensus_number: null,
          actual_number: '41.9',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA原油庫存',
          id: '1127553',
          previous_number: '303.6',
          consensus_number: '-175.9',
          actual_number: '-601.4',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA原油產量引伸需求數據',
          id: '1127557',
          previous_number: '1981.3',
          consensus_number: null,
          actual_number: '2073.8',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周EIA原油進口',
          id: '1127661',
          previous_number: '69.9',
          consensus_number: null,
          actual_number: '-121.8',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA取暖油庫存',
          id: '1127663',
          previous_number: '82.7',
          consensus_number: null,
          actual_number: '-50.3',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA成品油進口',
          id: '1127664',
          previous_number: '21.5',
          consensus_number: null,
          actual_number: '7.4',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周EIA戰略石油儲備庫存',
          id: '1127667',
          previous_number: '22.6',
          consensus_number: null,
          actual_number: '22.3',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA投產原油量',
          id: '1127666',
          previous_number: '5.6',
          consensus_number: null,
          actual_number: '2.8',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周EIA新配方汽油庫存',
          id: '1127662',
          previous_number: '0.1',
          consensus_number: null,
          actual_number: '0',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA汽油庫存',
          id: '1127555',
          previous_number: '-79.2',
          consensus_number: '-91.5',
          actual_number: '-272',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA汽油產量',
          id: '1127660',
          previous_number: '1',
          consensus_number: null,
          actual_number: '-25.9',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周EIA精煉廠設備利用率',
          id: '1127659',
          previous_number: '96.4',
          consensus_number: '95.7',
          actual_number: '96.6',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '當周EIA精煉油庫存',
          id: '1127556',
          previous_number: '71.4',
          consensus_number: '92.8',
          actual_number: '234.3',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶',
        },
        {
          display_title: '當周EIA精煉油產量',
          id: '1127665',
          previous_number: '3.2',
          consensus_number: null,
          actual_number: '19.3',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周EIA蒸餾燃油產量引伸需求數據',
          id: '1127559',
          previous_number: '514.2',
          consensus_number: null,
          actual_number: '511.93',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '當周EIA車用汽油總產量引伸需求數據',
          id: '1127558',
          previous_number: '982.47',
          consensus_number: null,
          actual_number: '986.16',
          revised_number: null,
          publish_at: '2025-08-20T14:30:00+00:00',
          country: 'USD',
          unit: '萬桶/日',
        },
        {
          display_title: '美聯儲理事沃勒在懷俄明州區塊鏈研討會上發表講話。',
          id: '1127741',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T15:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '4個月國債競拍-得標利率',
          id: '1127560',
          previous_number: '4.05',
          consensus_number: null,
          actual_number: '4.05',
          revised_number: null,
          publish_at: '2025-08-20T15:30:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '4個月國債競拍-投標倍數',
          id: '1127561',
          previous_number: '3.5',
          consensus_number: null,
          actual_number: '3.14',
          revised_number: null,
          publish_at: '2025-08-20T15:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '20年期國債競拍-得標利率',
          id: '1127563',
          previous_number: '4.94',
          consensus_number: null,
          actual_number: '4.876',
          revised_number: null,
          publish_at: '2025-08-20T17:00:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '20年期國債競拍-得標利率配置百分比',
          id: '1127668',
          previous_number: '85.3',
          consensus_number: null,
          actual_number: '44.44',
          revised_number: null,
          publish_at: '2025-08-20T17:00:00+00:00',
          country: 'USD',
          unit: '%',
        },
        {
          display_title: '20年期國債競拍-投標倍數',
          id: '1127562',
          previous_number: '2.79',
          consensus_number: null,
          actual_number: '2.54',
          revised_number: null,
          publish_at: '2025-08-20T17:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '美聯儲公布貨幣政策會議紀要。',
          id: '1125699',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T18:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title:
            'NYMEX紐約原油9月期貨受移倉換月影響，8月21日2:30完成場內最後交易，凌晨5:00完成電子盤最後交易，請留意交易場所到期換月公告控制風險。此外，部分交易平台美油合約到期時間通常較NYMEX官方提前一天，請多加留意。',
          id: '1014916',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T18:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title:
            '2027年FOMC票委、亞特蘭大聯儲主席博斯蒂克就經濟前景發表講話。',
          id: '1127428',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-20T19:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: 'PPI年率',
          id: '1127564',
          previous_number: '0.50',
          consensus_number: null,
          actual_number: '0.5',
          revised_number: '0.5',
          publish_at: '2025-08-20T21:00:00+00:00',
          country: 'KR',
          unit: '%',
        },
        {
          display_title: 'PPI月率',
          id: '1127669',
          previous_number: '0.1',
          consensus_number: null,
          actual_number: '0.4',
          revised_number: '0.1',
          publish_at: '2025-08-20T21:00:00+00:00',
          country: 'KR',
          unit: '%',
        },
        {
          display_title: '12個月貿易帳',
          id: '1127568',
          previous_number: '-43.66',
          consensus_number: null,
          actual_number: '-39.4',
          revised_number: '-43.8',
          publish_at: '2025-08-20T22:45:00+00:00',
          country: 'NZD',
          unit: '億紐元',
        },
        {
          display_title: '出口',
          id: '1127565',
          previous_number: '66.3',
          consensus_number: null,
          actual_number: '67.1',
          revised_number: '65.3',
          publish_at: '2025-08-20T22:45:00+00:00',
          country: 'NZD',
          unit: '億紐元',
        },
        {
          display_title: '貿易帳',
          id: '1127567',
          previous_number: '1.42',
          consensus_number: null,
          actual_number: '-5.78',
          revised_number: '2.03',
          publish_at: '2025-08-20T22:45:00+00:00',
          country: 'NZD',
          unit: '億紐元',
        },
        {
          display_title: '進口',
          id: '1127566',
          previous_number: '64.9',
          consensus_number: null,
          actual_number: '72.8',
          revised_number: '63.3',
          publish_at: '2025-08-20T22:45:00+00:00',
          country: 'NZD',
          unit: '億紐元',
        },
        {
          display_title: '標普全球制造業PMI初值',
          id: '1127570',
          previous_number: '51.3',
          consensus_number: null,
          actual_number: '52.9',
          revised_number: null,
          publish_at: '2025-08-20T23:00:00+00:00',
          country: 'AUD',
          unit: null,
        },
        {
          display_title: '標普全球服務業PMI初值',
          id: '1127571',
          previous_number: '54.1',
          consensus_number: null,
          actual_number: '55.1',
          revised_number: null,
          publish_at: '2025-08-20T23:00:00+00:00',
          country: 'AUD',
          unit: null,
        },
        {
          display_title: '標普全球綜合PMI初值',
          id: '1127569',
          previous_number: '53.8',
          consensus_number: null,
          actual_number: '54.9',
          revised_number: null,
          publish_at: '2025-08-20T23:00:00+00:00',
          country: 'AUD',
          unit: null,
        },
        {
          display_title: '當周外資買進日債',
          id: '1127574',
          previous_number: '7332',
          consensus_number: null,
          actual_number: '1979',
          revised_number: null,
          publish_at: '2025-08-20T23:50:00+00:00',
          country: 'JPY',
          unit: '億日元',
        },
        {
          display_title: '當周外資買進日股',
          id: '1127575',
          previous_number: '4893',
          consensus_number: null,
          actual_number: '11617',
          revised_number: '4955',
          publish_at: '2025-08-20T23:50:00+00:00',
          country: 'JPY',
          unit: '億日元',
        },
        {
          display_title: '當周買進外國債券',
          id: '1127572',
          previous_number: '2549',
          consensus_number: null,
          actual_number: '-3136',
          revised_number: '2547',
          publish_at: '2025-08-20T23:50:00+00:00',
          country: 'JPY',
          unit: '億日元',
        },
        {
          display_title: '當周買進外國股票',
          id: '1127573',
          previous_number: '-2255',
          consensus_number: null,
          actual_number: '3950',
          revised_number: null,
          publish_at: '2025-08-20T23:50:00+00:00',
          country: 'JPY',
          unit: '億日元',
        },
        {
          display_title: '制造業PMI初值',
          id: '1127577',
          previous_number: '48.9',
          consensus_number: null,
          actual_number: '49.9',
          revised_number: null,
          publish_at: '2025-08-21T00:30:00+00:00',
          country: 'JPY',
          unit: null,
        },
        {
          display_title: '服務業PMI初值',
          id: '1127578',
          previous_number: '53.6',
          consensus_number: null,
          actual_number: '52.7',
          revised_number: null,
          publish_at: '2025-08-21T00:30:00+00:00',
          country: 'JPY',
          unit: null,
        },
        {
          display_title: '綜合PMI初值',
          id: '1127576',
          previous_number: '51.6',
          consensus_number: null,
          actual_number: '51.9',
          revised_number: null,
          publish_at: '2025-08-21T00:30:00+00:00',
          country: 'JPY',
          unit: null,
        },
        {
          display_title: 'Swift人民幣在全球支付中佔比',
          id: '1127579',
          previous_number: '2.88',
          consensus_number: null,
          actual_number: '2.88',
          revised_number: null,
          publish_at: '2025-08-21T01:00:00+00:00',
          country: 'CNY',
          unit: '%',
        },
        {
          display_title: '今日有1287億元7天期逆回購到期。',
          id: '1127441',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-21T01:20:00+00:00',
          country: 'CNY',
          unit: null,
        },
        {
          display_title: '公共部門淨借款',
          id: '1127584',
          previous_number: '207',
          consensus_number: '26',
          actual_number: '10.54',
          revised_number: '225.6',
          publish_at: '2025-08-21T06:00:00+00:00',
          country: 'GBP',
          unit: '億英鎊',
        },
        {
          display_title: '季調後實際出口月率',
          id: '1127585',
          previous_number: '6.10',
          consensus_number: null,
          actual_number: '-2.7',
          revised_number: '7.3',
          publish_at: '2025-08-21T06:00:00+00:00',
          country: 'CHF',
          unit: '%',
        },
        {
          display_title: '季調後實際進口月率',
          id: '1127586',
          previous_number: '0.70',
          consensus_number: null,
          actual_number: '-0.3',
          revised_number: '0.9',
          publish_at: '2025-08-21T06:00:00+00:00',
          country: 'CHF',
          unit: '%',
        },
        {
          display_title: '政府收支短差',
          id: '1127583',
          previous_number: '-161',
          consensus_number: null,
          actual_number: '30.02',
          revised_number: '-163.67',
          publish_at: '2025-08-21T06:00:00+00:00',
          country: 'GBP',
          unit: '億英鎊',
        },
        {
          display_title: '貿易帳',
          id: '1127670',
          previous_number: '57.9',
          consensus_number: null,
          actual_number: '45.91',
          revised_number: '57.26',
          publish_at: '2025-08-21T06:00:00+00:00',
          country: 'CHF',
          unit: '億瑞郎',
        },
        {
          display_title: '全社會用電量同比',
          id: '1127310',
          previous_number: '5.4',
          consensus_number: null,
          actual_number: '8.6',
          revised_number: null,
          publish_at: '2025-08-21T06:54:00+00:00',
          country: 'CNY',
          unit: '%',
        },
        {
          display_title: '商務部召開8月第1次例行新聞發布會。',
          id: '1127782',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-21T07:00:00+00:00',
          country: 'CNY',
          unit: null,
        },
        {
          display_title: '全社會用電量',
          id: '1127311',
          previous_number: '8670',
          consensus_number: null,
          actual_number: '10226',
          revised_number: null,
          publish_at: '2025-08-21T07:04:00+00:00',
          country: 'CNY',
          unit: '億千瓦時',
        },
        {
          display_title: '制造業PMI初值',
          id: '1127587',
          previous_number: '48.2',
          consensus_number: '48',
          actual_number: '49.9',
          revised_number: null,
          publish_at: '2025-08-21T07:15:00+00:00',
          country: 'FR',
          unit: null,
        },
        {
          display_title: '服務業PMI初值',
          id: '1127588',
          previous_number: '48.5',
          consensus_number: '48.5',
          actual_number: '49.7',
          revised_number: null,
          publish_at: '2025-08-21T07:15:00+00:00',
          country: 'FR',
          unit: null,
        },
        {
          display_title: '綜合PMI初值',
          id: '1127589',
          previous_number: '48.6',
          consensus_number: '48.5',
          actual_number: '49.8',
          revised_number: null,
          publish_at: '2025-08-21T07:15:00+00:00',
          country: 'FR',
          unit: null,
        },
        {
          display_title: '制造業PMI初值',
          id: '1127590',
          previous_number: '49.1',
          consensus_number: '48.8',
          actual_number: '49.9',
          revised_number: null,
          publish_at: '2025-08-21T07:30:00+00:00',
          country: 'DE',
          unit: null,
        },
        {
          display_title: '服務業PMI初值',
          id: '1127591',
          previous_number: '50.6',
          consensus_number: '50.3',
          actual_number: '50.1',
          revised_number: null,
          publish_at: '2025-08-21T07:30:00+00:00',
          country: 'DE',
          unit: null,
        },
        {
          display_title: '綜合PMI初值',
          id: '1127592',
          previous_number: '50.6',
          consensus_number: '50.2',
          actual_number: '50.9',
          revised_number: null,
          publish_at: '2025-08-21T07:30:00+00:00',
          country: 'DE',
          unit: null,
        },
        {
          display_title: '制造業PMI初值',
          id: '1127593',
          previous_number: '49.8',
          consensus_number: '49.5',
          actual_number: '50.5',
          revised_number: null,
          publish_at: '2025-08-21T08:00:00+00:00',
          country: 'EUR',
          unit: null,
        },
        {
          display_title: '服務業PMI初值',
          id: '1127594',
          previous_number: '51',
          consensus_number: '50.8',
          actual_number: '50.7',
          revised_number: null,
          publish_at: '2025-08-21T08:00:00+00:00',
          country: 'EUR',
          unit: null,
        },
        {
          display_title: '綜合PMI初值',
          id: '1127595',
          previous_number: '50.9',
          consensus_number: '50.7',
          actual_number: '51.1',
          revised_number: null,
          publish_at: '2025-08-21T08:00:00+00:00',
          country: 'EUR',
          unit: null,
        },
        {
          display_title: '制造業PMI初值',
          id: '1127597',
          previous_number: '48',
          consensus_number: '48.3',
          actual_number: '47.3',
          revised_number: null,
          publish_at: '2025-08-21T08:30:00+00:00',
          country: 'GBP',
          unit: null,
        },
        {
          display_title: '服務業PMI初值',
          id: '1127598',
          previous_number: '51.8',
          consensus_number: '51.8',
          actual_number: '53.6',
          revised_number: null,
          publish_at: '2025-08-21T08:30:00+00:00',
          country: 'GBP',
          unit: null,
        },
        {
          display_title: '綜合CPI年率',
          id: '1127596',
          previous_number: '1.40',
          consensus_number: '0.8',
          actual_number: '1',
          revised_number: null,
          publish_at: '2025-08-21T08:30:00+00:00',
          country: 'HKD',
          unit: '%',
        },
        {
          display_title: '綜合PMI初值',
          id: '1127599',
          previous_number: '51.5',
          consensus_number: '51.6',
          actual_number: '53',
          revised_number: null,
          publish_at: '2025-08-21T08:30:00+00:00',
          country: 'GBP',
          unit: null,
        },
        {
          display_title: '建築業產出年率',
          id: '1127601',
          previous_number: '2.90',
          consensus_number: null,
          actual_number: '1.7',
          revised_number: null,
          publish_at: '2025-08-21T09:00:00+00:00',
          country: 'EUR',
          unit: '%',
        },
        {
          display_title: '建築業產出月率',
          id: '1127600',
          previous_number: '-1.70',
          consensus_number: null,
          actual_number: '-0.8',
          revised_number: '-2.14',
          publish_at: '2025-08-21T09:00:00+00:00',
          country: 'EUR',
          unit: '%',
        },
        {
          display_title: 'CBI工業物價預期差值',
          id: '1127603',
          previous_number: '21',
          consensus_number: null,
          actual_number: '9',
          revised_number: null,
          publish_at: '2025-08-21T10:00:00+00:00',
          country: 'GBP',
          unit: null,
        },
        {
          display_title: 'CBI工業訂單差值',
          id: '1127602',
          previous_number: '-30',
          consensus_number: '-28',
          actual_number: '-33',
          revised_number: null,
          publish_at: '2025-08-21T10:00:00+00:00',
          country: 'GBP',
          unit: null,
        },
        {
          display_title: '前聖路易斯聯儲主席布拉德發表講話。',
          id: '1128181',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-21T11:00:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '2025年FOMC票委、堪薩斯聯儲主席施密德發表講話。',
          id: '1128182',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-21T11:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title:
            '2027年FOMC票委、亞特蘭大聯儲主席博斯蒂克就經濟前景發表講話。',
          id: '1127440',
          previous_number: null,
          consensus_number: null,
          actual_number: null,
          revised_number: null,
          publish_at: '2025-08-21T11:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '原材料價格指數年率',
          id: '1127673',
          previous_number: '1.1',
          consensus_number: null,
          actual_number: '0.8',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: '原材料價格指數月率',
          id: '1127605',
          previous_number: '2.70',
          consensus_number: '-0.6',
          actual_number: '0.3',
          revised_number: '2.8',
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: '工業品物價指數年率',
          id: '1127672',
          previous_number: '1.7',
          consensus_number: null,
          actual_number: '2.6',
          revised_number: '1.9',
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: '工業品物價指數月率',
          id: '1127604',
          previous_number: '0.40',
          consensus_number: '0.3',
          actual_number: '0.7',
          revised_number: '0.5',
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'CAD',
          unit: '%',
        },
        {
          display_title: '當周初請失業金人數',
          id: '1127606',
          previous_number: '22.4',
          consensus_number: '22.5',
          actual_number: '23.5',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: '萬人',
        },
        {
          display_title: '當周初請失業金人數四周均值',
          id: '1127674',
          previous_number: '22.175',
          consensus_number: null,
          actual_number: '22.625',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: '萬人',
        },
        {
          display_title: '當周續請失業金人數',
          id: '1127607',
          previous_number: '195.3',
          consensus_number: '196',
          actual_number: '197.2',
          revised_number: '194.2',
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: '萬人',
        },
        {
          display_title: '費城聯儲制造業就業指數',
          id: '1127675',
          previous_number: '10.3',
          consensus_number: null,
          actual_number: '5.9',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '費城聯儲制造業指數',
          id: '1127608',
          previous_number: '15.9',
          consensus_number: '7',
          actual_number: '-0.3',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '費城聯儲制造業新訂單指數',
          id: '1127678',
          previous_number: '18.4',
          consensus_number: null,
          actual_number: '-1.9',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '費城聯儲制造業物價支付指數',
          id: '1127677',
          previous_number: '58.8',
          consensus_number: null,
          actual_number: '66.8',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '費城聯儲制造業物價獲得指數',
          id: '1127676',
          previous_number: '34.8',
          consensus_number: null,
          actual_number: '36.1',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '費城聯儲制造業裝船指數',
          id: '1127679',
          previous_number: '23.7',
          consensus_number: null,
          actual_number: '4.5',
          revised_number: null,
          publish_at: '2025-08-21T12:30:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '標普全球制造業PMI初值',
          id: '1127610',
          previous_number: '49.8',
          consensus_number: '49.5',
          actual_number: '53.3',
          revised_number: null,
          publish_at: '2025-08-21T13:45:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '標普全球服務業PMI初值',
          id: '1127611',
          previous_number: '55.7',
          consensus_number: '54.2',
          actual_number: '55.4',
          revised_number: null,
          publish_at: '2025-08-21T13:45:00+00:00',
          country: 'USD',
          unit: null,
        },
        {
          display_title: '標普全球綜合PMI初值',
          id: '1127612',
          previous_number: '55.1',
          consensus_number: '53.5',
          actual_number: '55.4',
          revised_number: null,
          publish_at: '2025-08-21T13:45:00+00:00',
          country: 'USD',
          unit: null,
        },
      ],
    },
  })

  return json
}
