coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  use-catch-all-next-params:
    paths:
      - "@packages/use-catch-all-next-params/"
    carryforward: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/vitest.config.ts"
  - "**/vitest.setup.ts"
  - "**/*.config.*"
  - "**/node_modules/**"
