packages:
  - "@apps/*"
  - "@packages/*/e2e/*"
  - "@packages/*"
  - "!**/test/**"
  - "!**/mock/**"
  - "!**/.vercel/**"

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@tailwindcss/oxide"
  - chinese-conv
  - esbuild
  - lefthook
  - sharp
  - supabase
