name: Test and Coverage for @onlywatch/use-catch-all-next-params

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: pnpm --filter="@onlywatch/use-catch-all-next-params" test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./@packages/use-catch-all-next-params
          flags: use-catch-all-next-params
          name: use-catch-all-next-params
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
